parameters:

    #
    # Entities
    #
    elcodi.core.currency.entity.currency.class: Elcodi\CurrencyBundle\Entity\Currency
    elcodi.core.currency.entity.currency_exchange_rate.class: Elcodi\CurrencyBundle\Entity\CurrencyExchangeRate

    #
    # Repositories
    #
    elcodi.core.currency.repository.currency.class: Elcodi\CurrencyBundle\Repository\CurrencyRepository
    elcodi.core.currency.repository.currency_exchange_rate.class: Elcodi\CurrencyBundle\Repository\CurrencyExchangeRateRepository

    #
    # Factories
    #
    elcodi.core.currency.factory.currency.class: Elcodi\CurrencyBundle\Factory\CurrencyFactory
    elcodi.core.currency.factory.currency_exchange_rate.class: Elcodi\CurrencyBundle\Factory\CurrencyExchangeRateFactory

    #
    # Services
    #
    elcodi.core.currency.service.currency_manager.class: Elcodi\CurrencyBundle\Services\CurrencyManager
    elcodi.core.currency.service.currency_converter.class: Elcodi\CurrencyBundle\Services\CurrencyConverter
    elcodi.core.currency.service.currency_session_manager.class: Elcodi\CurrencyBundle\Services\CurrencySessionManager

    #
    # Providers
    #
    elcodi.core.currency.service.exchange_rates_provider.class: Elcodi\CurrencyBundle\Services\ExchangeRatesProvider

    #
    # Twig extensions
    #
    elcodi.core.currency.twig_extension.print_money.class: Elcodi\CurrencyBundle\Twig\PrintMoneyExtension

    #
    # Wrappers
    #
    elcodi.core.currency.wrapper.currency.class: Elcodi\CurrencyBundle\Wrapper\CurrencyWrapper
