parameters:

    #
    # Factories
    #
    elcodi.abstract_factory.purchasable.class: Elcodi\Component\Currency\Factory\Abstracts\AbstractPurchasableFactory
    elcodi.factory.currency.class: Elcodi\Component\Currency\Factory\CurrencyFactory
    elcodi.factory.currency_exchange_rate.class: Elcodi\Component\Currency\Factory\CurrencyExchangeRateFactory

    #
    # Services
    #
    elcodi.manager.currency.class: Elcodi\Component\Currency\Services\CurrencyManager
    elcodi.converter.currency.class: Elcodi\Component\Currency\Services\CurrencyConverter
    elcodi.session_manager.currency.class: Elcodi\Component\Currency\Services\CurrencySessionManager
    elcodi.populator.currency_exchange_rate.class: Elcodi\Component\Currency\Populator\CurrencyExchangeRatesPopulator

    #
    # Providers
    #
    elcodi.provider.currency_exchange_rate.class: Elcodi\Component\Currency\Services\CurrencyExchangeRatesProvider

    #
    # Twig extensions
    #
    elcodi.twig_extension.print_money.class: Elcodi\Component\Currency\Twig\PrintMoneyExtension

    #
    # Wrappers
    #
    elcodi.wrapper.currency.class: Elcodi\Component\Currency\Wrapper\CurrencyWrapper

    #
    # Commands
    #
    elcodi.command.populate_currency_rates.class: Elcodi\Component\Currency\Command\CurrencyExchangeRatesPopulateCommand

    #
    # ExchangeRates Adapter
    #
    elcodi.adapter.currency_exchange_rate.open_exchange.class: Elcodi\Component\Currency\Adapter\CurrencyExchangeRatesProvider\OpenExchangeRatesProviderAdapter
    elcodi.adapter.currency_exchange_rate.dummy.class: Elcodi\Component\Currency\Adapter\CurrencyExchangeRatesProvider\DummyProviderAdapter

    #
    # ExpressionLanguage providers
    #
    elcodi.expression_language.money_provider.class: Elcodi\Component\Currency\ExpressionLanguage\MoneyProvider
