services:

    #
    # Commands
    #
    elcodi.command.populate_currency_rates:
        class: %elcodi.command.populate_currency_rates.class%
        arguments:
            - @elcodi.populator.currency_exchange_rate
        tags:
            -  { name: console.command }
