services:

    #
    # Commands
    #
    elcodi.core.currency.command.currency_exchange_rates_populate:
        class: %elcodi.core.currency.command.currency_exchange_rates_populate.class%
        arguments:
            currency_rates_populator: @elcodi.currency_rates_populator
        tags:
            -  { name: console.command }
