services:

    #
    # Specific provider for Currency Wrapper
    #
    elcodi.expression_language.money_provider:
        class: %elcodi.expression_language.money_provider.class%
        arguments:
            - @elcodi.wrapper.currency
            - @elcodi.repository.currency
        tags:
            - { name: elcodi.rule_configuration }
