services:

    #
    # Specific provider for Currency Wrapper
    #
    elcodi.core.currency.expression_language.money_provider:
        class: %elcodi.core.currency.expression_language.money_provider.class%
        arguments:
            - @elcodi.currency_wrapper
            - @elcodi.repository.currency
        tags:
            - { name: elcodi.rule_configuration }
