services:

    #
    # Factories
    #

    #
    # Factory for Currency entities
    #
    elcodi.core.currency.factory.currency:
        class: %elcodi.core.currency.factory.currency.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.currency.entity.currency.class%"]]

    elcodi.factory.currency:
        alias: elcodi.core.currency.factory.currency

    #
    # Factory for CurrencyExchangeRate entitites
    #
    elcodi.core.currency.factory.currency_exchange_rate:
        class: %elcodi.core.currency.factory.currency_exchange_rate.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.currency.entity.currency_exchange_rate.class%"]]

    elcodi.factory.currency_exchange_rate:
        alias: elcodi.core.currency.factory.currency_exchange_rate

    #
    # Entity providers
    #

    #
    # Instance provider for Currency entities
    #
    elcodi.core.currency.entity.currency.instance:
        class: %elcodi.core.currency.entity.currency.class%
        factory_service: elcodi.core.currency.factory.currency
        factory_method: create
        scope: prototype

    elcodi.entity.currency.instance:
        alias: elcodi.core.currency.entity.currency.instance

    #
    # Instance provider for default Currency
    #
    elcodi.core.currency.entity.default_currency.instance:
        class: %elcodi.core.currency.entity.currency.class%
        factory_service: elcodi.core.currency.wrapper.currency
        factory_method: getDefaultCurrency

    elcodi.entity.default_currency.instance:
        alias: elcodi.core.currency.entity.default_currency.instance

    #
    # Instance provider for CurrencyExchangeRate entities
    #
    elcodi.core.currency.entity.currency_exchange_rate.instance:
        class: %elcodi.core.currency.entity.currency_exchange_rate.class%
        factory_service: elcodi.core.currency.factory.currency_exchange_rate
        factory_method: create
        scope: prototype

    elcodi.entity.currency_exchange_rate.instance:
        alias: elcodi.core.currency.entity.currency_exchange_rate.instance
