services:

    #
    # Factories
    #

    #
    # Abstract purchasable factory
    #
    elcodi.factory.abstract.purchasable:
        class: %elcodi.abstract_factory.purchasable.class%
        abstract: true
        arguments:
            currency_wrapper: @elcodi.wrapper.currency

    #
    # Factory for Currency entities
    #
    elcodi.factory.currency:
        class: %elcodi.factory.currency.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.currency.class%"]]

    #
    # Factory for CurrencyExchangeRate entitites
    #
    elcodi.factory.currency_exchange_rate:
        class: %elcodi.factory.currency_exchange_rate.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.currency_exchange_rate.class%"]]
