services:

    #
    # Object Managers
    #
    elcodi.object_manager.currency:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.currency.entity.currency.class% ]

    elcodi.object_manager.currency_exchange_rate:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.currency.entity.currency_exchange_rate.class% ]
