services:

    #
    # Repositories
    #

    #
    # Repository for entity currency
    #
    elcodi.repository.currency:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.currency.entity.currency.class%

    #
    # Repository for entity currency_exchange_rate
    #
    elcodi.repository.currency_exchange_rate:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.currency.entity.currency_exchange_rate.class%
