services:

    #
    # Services
    #
    elcodi.manager.currency:
        class: %elcodi.manager.currency.class%
        arguments:
            - @elcodi.repository.currency
            - @elcodi.repository.currency_exchange_rate
            - %elcodi.core.currency.rates_provider_currency_base%

    elcodi.session_manager.currency:
        class: %elcodi.session_manager.currency.class%
        arguments:
            - @session
            - %elcodi.core.currency.session_field_name%

    elcodi.converter.currency:
        class: %elcodi.converter.currency.class%
        arguments:
            - @elcodi.manager.currency
            - %elcodi.core.currency.rates_provider_currency_base%

    elcodi.populator.currency_exchange_rate:
        class: %elcodi.populator.currency_exchange_rate.class%
        lazy: true
        arguments:
            - @elcodi.object_manager.currency_exchange_rate
            - @elcodi.repository.currency
            - @elcodi.repository.currency_exchange_rate
            - @elcodi.factory.currency_exchange_rate
            - @elcodi.provider.currency_exchange_rate
            - %elcodi.core.currency.default_currency%

    #
    # Providers
    #
    elcodi.provider.currency_exchange_rate:
        class: %elcodi.provider.currency_exchange_rate.class%
        arguments:
            - @elcodi.adapter.currency_exchange_rate

    #
    # Wrappers
    #
    elcodi.wrapper.currency:
        class: %elcodi.wrapper.currency.class%
        arguments:
            - @elcodi.session_manager.currency
            - @elcodi.repository.currency
            - %elcodi.core.currency.default_currency%
