services:

    #
    # Services
    #
    elcodi.manager.currency:
        class: Elcodi\Component\Currency\Services\CurrencyManager
        arguments:
            - @elcodi.repository.currency
            - @elcodi.repository.currency_exchange_rate
            - %elcodi.currency_rates_provider_currency_base%

    elcodi.manager.currency_session:
        class: Elcodi\Component\Currency\Services\CurrencySessionManager
        arguments:
            - @session
            - %elcodi.currency_session_field_name%

    elcodi.converter.currency:
        class: Elcodi\Component\Currency\Services\CurrencyConverter
        arguments:
            - @elcodi.manager.currency
            - %elcodi.currency_rates_provider_currency_base%

    elcodi.populator.currency_exchange_rate:
        class: Elcodi\Component\Currency\Populator\CurrencyExchangeRatesPopulator
        lazy: true
        arguments:
            - @elcodi.object_manager.currency_exchange_rate
            - @elcodi.repository.currency
            - @elcodi.repository.currency_exchange_rate
            - @elcodi.factory.currency_exchange_rate
            - @elcodi.provider.currency_exchange_rate
            - %elcodi.default_currency%

    #
    # Providers
    #
    elcodi.provider.currency_exchange_rate:
        class: Elcodi\Component\Currency\Services\CurrencyExchangeRatesProvider
        arguments:
            - @elcodi.adapter.currency_exchange_rate
