services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.print_money:
        class: %elcodi.twig_extension.print_money.class%
        arguments:
            - @elcodi.converter.currency
            - @elcodi.wrapper.currency
            - @elcodi.locale_iso
        tags:
            - { name: twig.extension }
