parameters:

    #
    # ElcodiLocaleProvider Adapter
    #
    elcodi.locale_provider_adapter.elcodi.class: Elcodi\Component\Currency\Adapter\LocaleProvider\ElcodiProviderAdapter

services:

    #
    # ElcodiLocaleProvider Adapter
    #
    elcodi.locale_provider_adapter.elcodi:
        class: %elcodi.locale_provider_adapter.elcodi.class%
        arguments:
            locale: @elcodi.locale

    elcodi.locale_provider_adapter:
        alias: elcodi.locale_provider_adapter.elcodi
