parameters:

    #
    # OpenExchangeRates Adapter
    #
    elcodi.core.currency.adapter.open_exchange_rates_adapter.class: Elcodi\CurrencyBundle\Adapter\OpenExchangeRatesAdapter

services:

    #
    # OpenExchangeRates Adapter
    #
    elcodi.core.currency.guzzle_client:
        class: Guzzle\Http\Client

    elcodi.core.currency.adapter.open_exchange_rates_adapter:
        class: %elcodi.core.currency.adapter.open_exchange_rates_adapter.class%
        arguments:
            guzzle_client: @elcodi.core.currency.guzzle_client
            api_id: %elcodi.core.currency.rates_provider_api_id%
            end_point: %elcodi.core.currency.rates_provider_endpoint%
            base_currency: %elcodi.core.currency.rates_provider_currency_base%

    elcodi.core.currency.adapter.exchange_rates_adapter:
        alias: elcodi.core.currency.adapter.open_exchange_rates_adapter
