parameters:

    #
    # ElcodiLocaleProvider Adapter
    #
    elcodi.core.currency.adapter.elcodi_locale_provider_adapter.class: Elcodi\Component\Currency\Adapter\LocaleProvider\ElcodiLocaleProviderAdapter

services:

    #
    # ElcodiLocaleProvider Adapter
    #
    elcodi.core.currency.adapter.elcodi_locale_provider_adapter:
        class: %elcodi.core.currency.adapter.elcodi_locale_provider_adapter.class%
        arguments:
            locale: @elcodi.locale

    elcodi.core.currency.adapter.locale_provider_adapter:
        alias: elcodi.core.currency.adapter.elcodi_locale_provider_adapter
